"""increase currency length

Revision ID: 5e5ca0e50415
Revises: 067fca1f1645
Create Date: 2026-06-06 19:17:21.878290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e5ca0e50415'
down_revision: Union[str, None] = '067fca1f1645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'currency',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'currency',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)
    # ### end Alembic commands ###
